name: Go

on: [ push, pull_request ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ 'windows', 'linux', 'darwin' ]
        include:
        - extension: ''
          script_extension: '.sh'
        - extension: '.exe'
          script_extension: '.bat'
          os: 'windows'
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.15

    - name: Build
      run: |
        cd mpv-discord 
        GOOS=${{ matrix.os }} GOARCH=amd64 go build -v -o ../bin/${{ matrix.os }}/mpv-discord${{ matrix.extension }}
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        name: mpv-discord_${{ matrix.os }}
        path: |
          bin/${{ matrix.os }}/mpv-discord${{ matrix.extension }}
          script-opts/
          scripts/
          install_${{ matrix.os }}${{ matrix.script_extension }}
          LICENSE.txt
          README.md

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3

    - name: Zip build artifacts
      run: |
        dir_name=$(find mpv-discord_* -maxdepth 0 -type d)
        for i in $dir_name; do pushd $i; zip -r ../$i *; popd; done

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: mpv-discord_*
